/**
 * Generate Pricing Configuration File
 *
 * Creates src/config/pricing.ts based on user's pricing plan configuration
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'

interface PlanConfig {
  id: string
  name: string
  price_monthly: number
  price_yearly: number
  stripe_price_id_monthly?: string
  stripe_price_id_yearly?: string
  features: string[]
  limits?: Record<string, number>
}

interface FeatureConfig {
  slug: string
  name: string
  description: string
  plans?: string[]
}

export async function generatePricingConfig(args: {
  project_path: string
  config: {
    plans: PlanConfig[]
    features: FeatureConfig[]
    metered_features?: Array<{ slug: string; unit_price: number; unit_name: string }>
    add_ons?: Array<{ id: string; name: string; price: number }>
  }
}) {
  const { project_path, config } = args

  const outputPath = join(project_path, 'src', 'config', 'pricing.ts')

  // Ensure directory exists
  const outputDir = dirname(outputPath)
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true })
  }

  // Generate TypeScript code
  const generatedCode = generatePricingTypescript(config)

  // Write to file
  writeFileSync(outputPath, generatedCode, 'utf-8')

  const summary = `
# ✅ Pricing Configuration Generated!

**File created:** \`${outputPath}\`

## Summary:

- **${config.plans.length} pricing plans** configured
- **${config.features.length} features** defined
${config.metered_features ? `- **${config.metered_features.length} metered features** for usage-based billing` : ''}
${config.add_ons ? `- **${config.add_ons.length} add-ons** available` : ''}

## Pricing Plans:

${config.plans.map((plan) => `
### ${plan.name} Plan
- **ID:** ${plan.id}
- **Price:** $${plan.price_monthly}/month or $${plan.price_yearly}/year
- **Features:** ${plan.features.length} included
${plan.features.map((f) => `  - ${f}`).join('\n')}
`).join('\n')}

## Next Steps:

1. **Set Stripe Price IDs:**
   - Go to https://dashboard.stripe.com/test/products
   - Create products for each plan
   - Add the price IDs to \`pricing.ts\`

2. **Update Supabase:**
   \`\`\`bash
   supabase db push
   \`\`\`

3. **Test Subscription Flow:**
   \`\`\`bash
   npm run dev
   \`\`\`

4. **Use Feature Gates:**
   \`\`\`tsx
   <SubscriptionGate slug="${config.features[0]?.slug || 'advanced-analytics'}">
     <YourPremiumComponent />
   </SubscriptionGate>
   \`\`\`

**Ready to gate components?** Run \`scan_codebase\` to find which components should be gated!
`

  return {
    content: [
      {
        type: 'text',
        text: summary,
      },
    ],
  }
}

function generatePricingTypescript(config: {
  plans: PlanConfig[]
  features: FeatureConfig[]
  metered_features?: Array<{ slug: string; unit_price: number; unit_name: string }>
  add_ons?: Array<{ id: string; name: string; price: number }>
}): string {
  const { plans, features, metered_features, add_ons } = config

  return `// Pricing Configuration
// Generated by Lovable Subscription Foundation MCP Server
// Last updated: ${new Date().toISOString()}

export const PRICING_CONFIG = {
  plans: {
${plans.map((plan) => `    ${plan.id}: {
      id: '${plan.id}' as const,
      name: '${plan.name}',
      price: {
        monthly: ${plan.price_monthly},
        yearly: ${plan.price_yearly},
      },
      stripe_price_ids: {
        monthly: '${plan.stripe_price_id_monthly || 'price_xxx_monthly'}',
        yearly: '${plan.stripe_price_id_yearly || 'price_xxx_yearly'}',
      },
      features: [
${plan.features.map((f) => `        '${f}',`).join('\n')}
      ] as const,
${plan.limits ? `      limits: ${JSON.stringify(plan.limits, null, 8)},` : ''}
    },`).join('\n')}
  },

  features: {
${features.map((feature) => `    '${feature.slug}': {
      slug: '${feature.slug}' as const,
      name: '${feature.name}',
      description: '${feature.description}',
      plans: [${(feature.plans || []).map((p) => `'${p}'`).join(', ')}] as const,
    },`).join('\n')}
  },
${metered_features ? `
  metered_features: {
${metered_features.map((mf) => `    '${mf.slug}': {
      slug: '${mf.slug}' as const,
      unit_price: ${mf.unit_price},
      unit_name: '${mf.unit_name}',
    },`).join('\n')}
  },
` : ''}${add_ons ? `
  add_ons: {
${add_ons.map((addon) => `    '${addon.id}': {
      id: '${addon.id}' as const,
      name: '${addon.name}',
      price: ${addon.price},
    },`).join('\n')}
  },
` : ''}
} as const

// Type exports
export type PlanId = keyof typeof PRICING_CONFIG.plans
export type FeatureSlug = keyof typeof PRICING_CONFIG.features
${metered_features ? `export type MeteredFeatureSlug = keyof typeof PRICING_CONFIG.metered_features` : ''}
${add_ons ? `export type AddOnId = keyof typeof PRICING_CONFIG.add_ons` : ''}

// Helper functions
export function getPlan(planId: PlanId) {
  return PRICING_CONFIG.plans[planId]
}

export function getFeature(featureSlug: FeatureSlug) {
  return PRICING_CONFIG.features[featureSlug]
}

export function isPlanFeatureIncluded(planId: PlanId, featureSlug: FeatureSlug): boolean {
  const feature = getFeature(featureSlug)
  return (feature.plans as readonly PlanId[]).includes(planId)
}

export function getPlansWithFeature(featureSlug: FeatureSlug): PlanId[] {
  const feature = getFeature(featureSlug)
  return [...feature.plans] as PlanId[]
}

export function getMinimumPlanForFeature(featureSlug: FeatureSlug): PlanId {
  const plans = getPlansWithFeature(featureSlug)
  const planOrder: PlanId[] = [${plans.map((p) => `'${p.id}'`).join(', ')}]

  for (const planId of planOrder) {
    if (plans.includes(planId)) {
      return planId
    }
  }

  throw new Error(\`Feature \${featureSlug} not available in any plan\`)
}
`
}
